-- 创建函数示例
CREATE FUNCTION add2num(INTEGER, INTEGER) RETURNS INTEGER
	AS
		'SELECT $1 + $2'
	LANGUAGE SQL
	RETURNS NULL ON NULL INPUT;
	
	
SELECT add2num(5, 7);

-- 实现 concat 函数
CREATE OR REPLACE FUNCTION concat_text(INTEGER, VARCHAR, DATE) RETURNS VARCHAR
	AS
		'SELECT $1 || $2 || $3'
	LANGUAGE SQL
	RETURNS NULL ON NULL INPUT;
	
	
-- 实现 concat 函数
CREATE OR REPLACE FUNCTION concat_text(INTEGER, VARCHAR) RETURNS VARCHAR
	AS
		'SELECT $1 || $2'
	LANGUAGE SQL
	RETURNS NULL ON NULL INPUT;
	
SELECT id, name, concat_text(id, name) FROM test